# Generated by Django 3.2 on 2021-04-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Contact', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=264)),
            ],
        ),
    ]
